"""Added sermon_date to Sermon

Revision ID: f42744a3b77e
Revises: 
Create Date: 2026-07-01 14:12:32.265219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42744a3b77e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sermon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url_1', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('audio_url_2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('sermon_date', sa.Date(), nullable=False))
        batch_op.drop_column('audio_file_2')
        batch_op.drop_column('audio_file_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sermon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_file_1', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('audio_file_2', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('sermon_date')
        batch_op.drop_column('audio_url_2')
        batch_op.drop_column('audio_url_1')

    # ### end Alembic commands ###
